/**
 * Frames from the journey — photography grids.
 */
export const workSamples = [
  "/work-samples/sample-01.jpg",
  "/work-samples/sample-02.jpg",
  "/work-samples/sample-03.jpg",
  "/work-samples/sample-04.jpg",
  "/work-samples/sample-05.jpg",
  "/work-samples/sample-06.jpg",
  "/work-samples/sample-07.jpg",
  "/work-samples/sample-08.jpg",
  "/work-samples/sample-09.jpg",
  "/work-samples/sample-10.jpg",
  "/work-samples/sample-11.jpg",
  "/work-samples/sample-12.jpg",
  "/work-samples/sample-13.jpg",
  "/work-samples/sample-14.jpg",
  "/work-samples/sample-15.jpg",
  "/work-samples/sample-16.jpg",
  "/work-samples/sample-17.jpg",
  "/work-samples/sample-18.jpg",
  "/work-samples/sample-19.jpg",
  "/work-samples/sample-20.jpg",
] as const;

export const workSamplesXl = [
  "/work-samples/xl-01.jpg",
  "/work-samples/xl-02.jpg",
  "/work-samples/xl-03.jpg",
  "/work-samples/xl-04.jpg",
  "/work-samples/xl-05.jpg",
  "/work-samples/xl-06.jpg",
  "/work-samples/xl-07.jpg",
  "/work-samples/xl-08.jpg",
  "/work-samples/xl-09.jpg",
  "/work-samples/xl-10.jpg",
  "/work-samples/xl-11.jpg",
  "/work-samples/xl-12.jpg",
  "/work-samples/xl-13.jpg",
  "/work-samples/xl-14.jpg",
  "/work-samples/xl-15.jpg",
  "/work-samples/xl-16.jpg",
  "/work-samples/xl-17.jpg",
  "/work-samples/xl-18.jpg",
  "/work-samples/xl-19.jpg",
  "/work-samples/xl-20.jpg",
  "/work-samples/xl-21.jpg",
  "/work-samples/xl-22.jpg",
  "/work-samples/xl-23.jpg",
  "/work-samples/xl-24.jpg",
  "/work-samples/xl-25.jpg",
  "/work-samples/xl-26.jpg",
  "/work-samples/xl-27.jpg",
  "/work-samples/xl-28.jpg",
  "/work-samples/xl-29.jpg",
  "/work-samples/xl-30.jpg",
] as const;
